import { Inter, Urbanist } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Session from "@/components/sessionProviders/SessionProvider";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Footers from "@/components/Footers/Footers";


const Urbanistt = Urbanist({ subsets: ["latin"] });

export const metadata = {
  title:{
    template:"Shopping Mart",
    default:"Shopping Mart A Place For All"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${Urbanistt.className} bg-main-bg w-full   text-darkText`}
      >
        <Session>
          <Header />
          {children}
          <Footers />
        </Session>
      </body>
    </html>
  );
}
